name: CPP CI

on:
  pull_request:

jobs:
  build_ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt install libboost-dev

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build
          cmake -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build -j $(nproc)

      - name: Run unit tests
        run: ./tests -d yes

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          $Url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.72.0/boost_1_72_0-msvc-14.2-64.exe"
          (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
          Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\hostedtoolcache\windows\Boost\1.72.0\x86_64"
          $env:BOOST_ROOT="C:\hostedtoolcache\windows\Boost\1.72.0\x86_64"
          mkdir build
          cmake -B build
          cmake --build build -j $(nproc) --config Release

      - name: Run unit tests
        run: ./Release/tests -d yes
